### ISSUE TITLE
Verhandlungsassistent öffnet sich nicht

### ISSUE THREAD

**Issue by moritzhckr** [sdn-br/foe-toolbox#10]
Verhandlungsassistent kann in GvG nicht geöffnet.

**Comment by sdn-br** [comment]
In GvG gibt es keine Verhandlungen, denke du meinst GG. Der Verhandlungsassistent für die Gildengefechte kann, sofern gewünscht, über die Einstellungen aktiviert werden. Schau mal in die Einstellungen, da gibt es eine entsprechende Option
