### ISSUE TITLE
PVP Angriffe

### ISSUE THREAD

**Issue by sukalopp** [sdn-br/foe-toolbox#11]
Gibt es die Möglichkeiten bei den PVP Angriffen kleine Bilder anzuzeigen anstelle der Grünen und Roten Balken?

**Comment by sdn-br** [comment]
Hallo sukalopp,
welche Art von Bildern hast du dir da so vorgestellt?

**Comment by sukalopp** [comment]
So Miniatur-Bilder von den Einheiten. Man kann ja beim drüber halten mit der Maus die Einheiten lesen aber visuell mit Bildern wäre ein Traum.

**Comment by sdn-br** [comment]
Ok, ich schau mir das mal an. Da sollten eigentlich Bilder sein. Muss sich seitens Inno wohl irgendwas geändert haben :)

**Comment by sdn-br** [comment]
Fixed in 1.19.1.0
